# Zadanie 1

In [38]:
import numpy as np
from math import sqrt
from time import time


def GaussJordan(A, b):
    size = len(A)

    A = np.concatenate((A, b.T), axis=1)

    for i in range(size):
        
        # find pivot
        pivot, pivotIdx = A[i][i], i
        for j in range(i+1, size):
            if abs(A[j][i]) > abs(pivot):
                pivot = A[j][i]
                pivotIdx = j

        # swap i-th with pivot
        if i != pivotIdx:
            A[[i, pivotIdx]] = A[[pivotIdx, i]]

        # reduce all rows
        for j in range(size):
            if j != i:
                A[j] -= (A[j][i] / A[i][i]) * A[i]
                A[j][i] = 0
    
    return [A[i][-1]/ A[i][i] for i in range(size)]

PRINTRESULT = True
SIZE = 10

A = np.float32(np.random.randint(0, 10, [SIZE, SIZE]))
b = np.array([np.random.randint(0, 10, SIZE)])
RIGHT = np.linalg.solve(A, b.T)
MYRESULT = GaussJordan(A, b)

if PRINTRESULT:
    for i in range(SIZE):
        print(f"Correct: {RIGHT[i][0]:>20}, My result: {MYRESULT[i]:>20}")

print("Benchmark")
for n in range(500, 1500, 200):
    A = np.float32(np.random.randint(0, 10, [n, n]))
    b = np.array([np.random.randint(0, 10, n)])

    print("Test size =", n)

    libStart = time()
    RIGHT = np.linalg.solve(A, b.T)
    print("Lib took:", time() - libStart)

    myStart = time()
    MYRESULT = GaussJordan(A, b)
    print("My  took:", time() - myStart)

Benchmark
Test size = 500
Lib took: 0.20280742645263672
My  took: 1.189450979232788
Test size = 700
Lib took: 0.019753217697143555
My  took: 1.5470285415649414
Test size = 900
Lib took: 0.025452613830566406
My  took: 2.7489516735076904
Test size = 1100
Lib took: 0.027765989303588867
My  took: 4.3326921463012695
Test size = 1300
Lib took: 0.05028581619262695
My  took: 6.3463263511657715


# Zadanie 2

In [85]:
def LUDecomp(A):
    size = len(A)

    for i in range(size):
        
        # reduce all rows
        for j in range(i, size):
            if j != i:
                scalingFactor = -(A[j][i] / A[i][i])
                A[j] += scalingFactor * A[i]
                A[j][i] = scalingFactor

    U = np.triu(A)
    L = np.tril(A)
    np.fill_diagonal(L, 1)
    return U, L

C = np.float32(np.random.randint(0, 10, [SIZE, SIZE]))
print(C)
U, L = LUDecomp(C)
# wydaje mi sie ze zle wykonuje funckje np.tril() poniewaz pierwszy wiersz nie jest zapisywany w U
print(max((C - np.dot(L, U)).flatten())) # 2 norma macierz C - UL

[[7. 9. 4. 9. 0. 2. 1. 1. 5. 2.]
 [4. 1. 5. 8. 3. 8. 3. 1. 6. 4.]
 [4. 7. 4. 2. 4. 6. 8. 5. 9. 2.]
 [0. 7. 0. 6. 6. 8. 9. 9. 2. 9.]
 [9. 6. 8. 7. 9. 2. 3. 5. 9. 3.]
 [4. 3. 4. 9. 2. 2. 1. 8. 8. 9.]
 [3. 3. 2. 3. 3. 2. 9. 7. 4. 5.]
 [5. 8. 9. 1. 9. 3. 9. 2. 1. 3.]
 [2. 5. 2. 4. 9. 3. 8. 1. 7. 9.]
 [6. 4. 9. 5. 6. 1. 4. 8. 0. 8.]]
23.560286
